### ISSUE TITLE
Cannot broadcast input array to size (1) 

### ISSUE THREAD

**Issue by julclu** [YixingHuang/DeepMedicPlus#11]
Hello - 
I cannot seem to figure out why the code is throwing this exception: 
 ERROR: Caught exception in do_training(): could not broadcast input array from shape (37,37,37) into shape (1)

partial traceback: 
```
2023-6-30 16:33:49.48: [TRA|SAMPLER|PID:2552997] :=:=:=:=:=:= Finished sampling for next [Training] =:=:=:=:=:=:
2023-6-30 16:33:49.52: 

 ERROR: Caught exception in do_training(): could not broadcast input array from shape (37,37,37) into shape (1)

2023-6-30 16:33:49.53: Traceback (most recent call last):
  File "/projects/site/pred/oncology_imaging/cluceruj/brain_mets/software/DeepMedicPlus/DeepMedicPlus/deepmedic/routines/training.py", line 332, in do_training
    lbls_samples_per_path_tr) = sampling_job_tr.get()
  File "/projects/site/pred/oncology_imaging/cluceruj/brain_mets/conda_env/deepmedic/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/projects/site/pred/oncology_imaging/cluceruj/brain_mets/conda_env/deepmedic/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/projects/site/pred/oncology_imaging/cluceruj/brain_mets/software/DeepMedicPlus/DeepMedicPlus/deepmedic/dataManagement/sampling.py", line 198, in get_samples_for_subepoch
    channs_of_samples_for_path in channs_of_samples_per_path]
  File "/projects/site/pred/oncology_imaging/cluceruj/brain_mets/software/DeepMedicPlus/DeepMedicPlus/deepmedic/dataManagement/sampling.py", line 198, in <listcomp>
    channs_of_samples_for_path in channs_of_samples_per_path]
  File "/projects/site/pred/oncology_imaging/cluceruj/brain_mets/conda_env/deepmedic/lib/python3.6/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (37,37,37) into shape (1)
```

Can you please help?

**Comment by YixingHuang** [comment]
Will [this issue](https://github.com/deepmedic/deepmedic/issues/70) from DeepMedic repository help you?

**Comment by julclu** [comment]
I got it - it was that i was not using prior images that were registered to the current image, causing a shape issue.
