### ISSUE TITLE
List index out of range when running inference on multiple cases

### ISSUE THREAD

**Issue by damiankucharski** [YixingHuang/DeepMedicPlus#7]
Hi @YixingHuang, I am trying to run predictions on multiple scans. However whenever I put more than two files in configs I am getting this error. Do you have any idea how it could be solved?

```
========== Done with printing session's parameters ==========
=============================================================
CONFIG: The configuration file for the [session] was loaded from: /home/kucharsd/Documents/Git/DeepMedicPlus/DeepMedicPlus/examples/configFiles/deepMedicPlus/test/testConfig.cfg

ERROR: Caught exception from main process: list index out of range
Traceback (most recent call last):
  File "/home/kucharsd/Documents/Git/DeepMedicPlus/DeepMedicPlus/deepMedicRun", line 175, in <module>
    _ = session.compile_session_params_from_cfg(model_params)
  File "/home/kucharsd/Documents/Git/DeepMedicPlus/DeepMedicPlus/deepmedic/frontEnd/testSession.py", line 43, in compile_session_params_from_cfg
    self._params = TestSessionParameters(self._log,
  File "/home/kucharsd/Documents/Git/DeepMedicPlus/DeepMedicPlus/deepmedic/frontEnd/configParsing/testSessionParams.py", line 127, in __init__
    self._make_fpaths_for_preds_and_fms(out_folder_preds, out_folder_fms)
  File "/home/kucharsd/Documents/Git/DeepMedicPlus/DeepMedicPlus/deepmedic/frontEnd/configParsing/testSessionParams.py", line 135, in _make_fpaths_for_preds_and_fms
    fpaths_for_case_pred = out_folder_preds + "/" + self.out_preds_fnames[case_i]
IndexError: list index out of range

Finished.
```

**Comment by damiankucharski** [comment]
I fixed the problem on my side.
